accessLogsFile = "/dev/stdout"
defaultEntryPoints = ["http", "https"]
logLevel = "ERROR"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
  [entryPoints.metrics]
    address = ":8080"
    [entryPoints.metrics.auth]
      [entryPoints.metrics.auth.basic]
        users = ["admin:$apr1$KHY0iGCR$bt6nCOlg0IIJAUVdYoJTa1"]

[api]
  entryPoint = "metrics"

[acme]
  email = "traefik@devslash.me"
  storage = "/acme/acme.json"
  entryPoint = "https"
  onHostRule = true
  logging = true

[acme.httpChallenge]
  entryPoint = "http"

[docker]
  domain = "devslash.me"
  exposedByDefault = false
  watch = true
  swarmmode = true
