version: '3'

services:
  traefik:
    build:
      context: ./traefik
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    networks:
      - traefik-net
    volumes:
      - traefik_acme:/acme/
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.port=8080"
      - "traefik.backend=traefik-backend"
      - "traefik.frontend.rule=Host:traefik.nucoder.io"
      - "traefik.enable=true"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  visualizer:
    image: dockersamples/visualizer:latest
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.port=8080"
      - "traefik.backend=visualizer-backend"
      - "traefik.frontend.rule=Host:docker.nucoder.io"
      - "traefik.enable=true"
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  traefik_acme:

networks:
  traefik-net:
    external: true

