version: '3.3'

services:
  traefik:
    image: traefik:latest
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.toml
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    networks:
      - traefik-net
    volumes:
      - traefik_acme:/acme/
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  visualizer:
    image: dockersamples/visualizer:latest
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.backend=visualizer-backend"
        - "traefik.frontend.rule=Host:docker.nucoder.io"
        - "traefik.enable=true"
      placement:
        constraints:
          - node.role == manager

configs:
  traefik_config:
    file: ./etc/traefik/traefik.toml

volumes:
  traefik_acme:

networks:
  traefik-net:
    external: true

