version: '3.3'

services:
  traefik:
    image: traefik:latest
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.toml
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik-net
    volumes:
      - traefik-acme:/acme/
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 20s

  visualizer:
    image: dockersamples/visualizer:latest
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.backend=visualizer-backend"
        - "traefik.frontend.rule=Host:docker.devslash.me"
        - "traefik.enable=true"
      placement:
        constraints:
          - node.role == manager

configs:
  traefik_config:
    file: ./etc/traefik/traefik.toml

volumes:
  traefik-acme:
    driver: rexray
    driver_opts:
      size: 2

networks:
  traefik-net:
    external: true

