version: '3'

services:
  postgres_primary:
    image: crunchydata/crunchy-postgres:centos7-10.5-2.1.0
    environment:
      - PG_MODE=primary
    env_file:
      - postgresql.env
    volumes:
      - pg-primary-vol:/pgdata
    networks:
      - postgresql
    deploy:
      placement:
        constraints:
          - node.labels.type == primary
          - node.role == worker

  postgres_replica:
    image: crunchydata/crunchy-postgres:centos7-10.5-2.1.0
    environment:
      - PG_MODE=replica
    env_file:
      - postgresql.env
    volumes:
      - pg-replica-vol:/pgdata
    networks:
      - postgresql
    deploy:
      placement:
        constraints:
          - node.labels.type != primary
          - node.role == worker

networks:
  postgresql

volumes:
  pg-primary-vol:
  pg-replica-vol:
