version: '3'

services:
  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - mattermost-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost

  app:
    build:
      context: app
    restart: unless-stopped
    networks:
      - traefik-net
    volumes:
      - mattermost-app:/mattermost
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
    deploy:
      labels:
        - "traefik.port=8000"
        - "traefik.backend=mattermost-backend"
        - "traefik.frontend.rule=Host:mattermost.nucoder.io"
        - "traefik.enable=true"

volumes:
  mattermost-app:
    driver: rexray
    driver_opts:
      size: 10
  mattermost-db:
    driver: rexray
    driver_opts:
      size: 2

networks:
  traefik-net:
    external: true


