version: '3.3'

services:
  db:
    image: mariadb
    volumes:
      - mattermost-db:/var/lib/mysql
    networks:
      - internal
    secrets:
      - mattermost_user
      - mattermost_password
      - mattermost_db
      - mattermost_db_root_password
    environment:
      - MYSQL_USER_FILE=/run/secrets/mattermost_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mattermost_password
      - MYSQL_DATABASE_FILE=/run/secrets/mattermost_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mattermost_db_root_password
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s

  app:
    image: kincerb/mattermost:5.14.1
    depends_on:
      - db
    networks:
      - internal
      - traefik-net
    volumes:
      - mattermost-data:/mattermost/data
      - mattermost-logs:/mattermost/logs
      - mattermost-config:/mattermost/config
      - mattermost-plugins:/mattermost/plugins
      - mattermost-client-plugins:/mattermost/client/plugins
    secrets:
      - mattermost_user
      - mattermost_password
      - mattermost_db
    environment:
      - MM_USERNAME_FILE=/run/secrets/mattermost_user
      - MM_PASSWORD_FILE=/run/secrets/mattermost_password
      - MM_DBNAME_FILE=/run/secrets/mattermost_db
      - DB_HOST=db
      - DB_PORT_NUMBER=3306
    deploy:
      labels:
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"
        - "traefik.port=8000"
        - "traefik.backend=mattermost"
        - "traefik.frontend.rule=Host:mattermost.devslash.me"
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s

volumes:
  mattermost-logs:
    driver: "rexray/dobs"
    driver_opts:
      size: 1
  mattermost-plugins:
    driver: "rexray/dobs"
    driver_opts:
      size: 1
  mattermost-client-plugins:
    driver: "rexray/dobs"
    driver_opts:
      size: 1
  mattermost-config:
    driver: "rexray/dobs"
    driver_opts:
      size: 1
  mattermost-data:
    driver: "rexray/dobs"
    driver_opts:
      size: 5
  mattermost-db:
    driver: "rexray/dobs"
    driver_opts:
      size: 2

networks:
  internal:
    driver: overlay
    external: false
  traefik-net:
    external: true

secrets:
  mattermost_user:
    external: true
  mattermost_password:
    external: true
  mattermost_db:
    external: true
  mattermost_db_root_password:
    external: true
