version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - mattermost-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - mattermost_user
      - mattermost_password
      - mattermost_db
    environment:
      - POSTGRES_USER_FILE=/run/secrets/mattermost_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/mattermost_password
      - POSTGRES_DB_FILE=/run/secrets/mattermost_db
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s

  app:
    image: kincerb/mattermost:5.3.1
    depends_on:
      - db
    networks:
      - traefik-net
    volumes:
      - mattermost-app:/mattermost
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - mattermost_user
      - mattermost_password
      - mattermost_db
    environment:
      - MM_USERNAME=/run/secrets/mattermost_user
      - MM_PASSWORD=/run/secrets/mattermost_password
      - MM_DBNAME=/run/secrets/mattermost_db
    deploy:
      labels:
        - "traefik.port=8000"
        - "traefik.backend=mattermost-backend"
        - "traefik.frontend.rule=Host:mattermost.nucoder.io"
        - "traefik.enable=true"
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s

volumes:
  mattermost-app:
    driver: rexray
    driver_opts:
      size: 10
  mattermost-db:
    driver: rexray
    driver_opts:
      size: 2

networks:
  traefik-net:
    external: true

secrets:
  mattermost_user:
    external: true
  mattermost_password:
    external: true
  mattermost_db:
    external: true

