version: '3.3'

services:
  db:
    image: mariadb
    networks:
      - internal
    volumes:
      - mattermost-db:/var/lib/mysql
    secrets:
      - mattermost_user
      - mattermost_password
      - mattermost_db
      - mattermost_db_root_password
    environment:
      - MYSQL_USER_FILE=/run/secrets/mattermost_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mattermost_password
      - MYSQL_DATABASE_FILE=/run/secrets/mattermost_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mattermost_db_root_password
    deploy:
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s

  app:
    image: kincerb/mattermost:5.7.0
    depends_on:
      - db
    networks:
      - internal
      - traefik-net
    volumes:
      - mattermost-app:/mattermost
    secrets:
      - mattermost_user
      - mattermost_password
      - mattermost_db
    environment:
      - MM_USERNAME_FILE=/run/secrets/mattermost_user
      - MM_PASSWORD_FILE=/run/secrets/mattermost_password
      - MM_DBNAME_FILE=/run/secrets/mattermost_db
      - DB_HOST=db
      - DB_PORT_NUMBER=3306
    deploy:
      labels:
        - "traefik.port=8000"
        - "traefik.backend=mattermost"
        - "traefik.frontend.rule=Host:mattermost.nucoder.io"
        - "traefik.enable=true"
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s

volumes:
  mattermost-app:
    driver: rexray
    driver_opts:
      size: 10
  mattermost-db:
    driver: rexray
    driver_opts:
      size: 2

networks:
  internal:
    external: false
    driver: overlay
  traefik-net:
    external: true

secrets:
  mattermost_user:
    external: true
  mattermost_password:
    external: true
  mattermost_db:
    external: true
  mattermost_db_root_password:
    external: true
