version: '3.3'

services:
  ghost:
    image: ghost:latest
    deploy:
      labels:
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"
        - "traefik.port=2368"
        - "traefik.backend=ghost"
        - "traefik.frontend.rule:Host:blog.nucoder.io"
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost

    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example
